# mail-sender Kubernetes deployment and ingress YAML

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-sender
  labels:
    app: mail-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-sender
  template:
    metadata:
      labels:
        app: mail-sender
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: mail-sender
          image: chrptvn/mail-sender:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_EMAIL
              value: "client@infocle.ca"
            - name: TO_EMAIL
              value: "christian.potvin@infocle.ca"
---
apiVersion: v1
kind: Service
metadata:
  name: mail-sender
spec:
  type: ClusterIP
  selector:
    app: mail-sender
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mail-sender-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:4200"
    nginx.ingress.kubernetes.io/cors-allow-methods: "POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: $upstream_http_access_control_allow_origin";
      more_set_headers "Access-Control-Allow-Methods: $upstream_http_access_control_allow_methods";
      more_set_headers "Access-Control-Allow-Headers: $upstream_http_access_control_allow_headers";
      more_set_headers "Access-Control-Allow-Credentials: $upstream_http_access_control_allow_credentials";

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - api.infocle.ca
      secretName: api-infocle-tls

  rules:
    - host: infocle.ca
      http:
        paths:
          - path: /v1/send_mail
            pathType: Prefix
            backend:
              service:
                name: mail-sender
                port:
                  number: 8080
